name: Deploy Frontend to VM Azure

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend-azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Frontend
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e

            echo "== Sync code with main =="
            cd ${{ secrets.VM_APP_DIR }}
            git fetch origin
            git reset --hard origin/main

            echo "== Frontend: install dependencies =="
            cd frontend
            npm install

            echo "== Frontend: build =="
            npm run build

            echo "== Frontend: restart PM2 process =="
            /home/fwc/.nvm/versions/node/v20.19.6/bin/pm2 restart fwc-frontend
          EOF